### PR TITLE
API Refactoring

### LINKED ISSUE #40: Make response fields private
For future compatibility, we should make the fields on responses private. This means reworking a few of them that have nested iterators but gives us the option to change the underlying types of things.

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #40 

This is an early work in progress to make the fields on the various response types private.

So far I've just done the `BulkResponse` types and added iterators to them. `SearchResponse` is probably the biggest type so will do it next.

### CODE REVIEW

**Comment by KodrAus** [comment]
I'm also looking at removing the default response types where the generic is replaced with `Value`. It's a bit unfortunate because it's so convenient, but means other APIs taking responses as input (for whatever reason) may end up just supporting just the default value.

I think we can get some ergonomics back by re-exporting `serde_json::Value` or `serde_json::Map<String, Value>` in the crate.

**Comment by KodrAus** [comment]
One thing that bothers me about losing all the public fields is that now we can't partially move out of the response types anymore.

For the bulk responses I've implemented `IntoIter` so you can take ownership of the bulk operations.

For the search response I'm thinking having the following iterators:

```rust
hits(&self) -> Hits: Iterator<&Hit<T>>
into_hits(self) -> IntoHits: Iterator<Hit<T>>

documents(&self) -> Documents: Iterator<&T>
into_documents(self) -> IntoDocuments: Iterator<T>

aggs(&self) -> Aggs: Iterator<&Aggregation>
into_aggs(self) -> IntoAggs: Iterator<Aggregation>
```

The `aggs` might need to change a bit. I think the iterator constructs them as they're requested. We might have to do that in deserialisation if aggregations are present. Not too sure yet.

Also not sure if there's a case where one might want to split and take ownership of the separate iterators:

```rust
SearchIter {
    pub hits: IntoHits<T>,
    pub Aggs: IntoAggs
}

let SearchIter { hits, aggs } = response.into();
```

Could bike-shed the names. But that means we've only got this one simple structure for pattern matching on, and the rest can change independently.

**Comment by KodrAus** [comment]
I'll just get the docs up to date, I want to add some more detail to the fields, add some examples for the search response iterators and then make sure this API covers everything we want.

**Comment by KodrAus** [comment]
@stephanbuys This is a pretty significant change, did you want to have a quick look through it? The gist of it is:
- Struct fields are now all private. We've got methods to access them instead
- Removes the default document generic from documents, so now you need to supply it
- Re-exports `serde_json::Value` so it's convenient to create responses with anonymous documents
- Fixed some `unwrap`s in the aggregation parser

**Comment by stephanbuys** [comment]
@KodrAus cool, will have a look.

**Comment by stephanbuys** [comment]
@KodrAus, just one small comment, perhaps add an example (apologies if there's already one - didn't spot it in the diffs) of a non-`Value` type being used when deserialising?

**Comment by KodrAus** [comment]
Good call! I'll add in another sample and a test using a strongly-typed document.

I need to do some more work on the docs in general, especially those new iterators so it's clear what they return, but I don't think that needs to block this change.

**Pull request merged**
