### PR TITLE
Feat/more response types

### LINKED ISSUE #6: Flesh out Hits type
The generic `Deserialize` stuff I did is actually broken, because the `T` used for the hits type then needs to specify all the meta properties:

```json
{
  "_index" : "typed_sample_index",
  "_type" : "mytype",
  "_id" : "AVmGgFk0Y2GdL7rFge-6",
  "_score" : 1.0,
  "_source" : {
    "id" : 1,
    "title" : "A title"
  }
}
```

Maybe we can flesh out the `Hit` struct to hold this data and use the `_source` field for the `T`?

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #6 

- Adds an `ApiError` type for deserialising REST API errors. There's an `enum` in there for pulling specific properties of interest off. If it doesn't recognise the response type then it'll just return the `serde_json::Value`.
- Renames `Response` to `QueryResponse` and adds `GetDocResponse` for calls to `/index/type/id`
- Fleshes out `Hit` type with more meta properties
- Uses `Hit` type by default in `Response`
- Rename fields to not start with an `_`. In Rust, a field that starts with `_` means it's unused and you'll get compiler warnings if you do anything with it. Instead I'm using `sere` attributes to rename them so they still parse properly

I also ran [`cargo fmt`](https://github.com/rust-lang-nursery/rustfmt) over the source.

There are a bunch of proposed changes, so feel free to push back on anything you don't agree with.

### CODE REVIEW

**Comment by KodrAus** [comment]
I also haven't implemented the standard `Error` trait for `ApiError`, because I was planning to create an [`error_chain`](https://github.com/brson/error-chain) for this library that would wrap it up. That'll take care of any `unwrap()`s when parsing aggregations too.

**Comment by KodrAus** [comment]
Sorry I probably could've broken this PR up into smaller pieces but I got on a roll :)

**Comment by KodrAus** [comment]
I'm going to tweak the error type a bit so it's nicer for pattern matching.

**Comment by KodrAus** [comment]
Hmm, now I'm wondering if `QueryResponse` should really be called `SearchResponse`...

**Comment by stephanbuys** [comment]
@KodrAus apologies for the delayed response, have been swamped at work - reviewing now - it looks awesome.

**Comment by stephanbuys** [comment]
@KodrAus ok, merged, please add yourself to the authors, I think at this point it more accurately reflects the situation :-)

**Comment by KodrAus** [comment]
@stephanbuys no problem! I've gotten into a bad habit of starting a PR and then snowballing a bunch of random things into it as I think of them. It makes it hard to focus on certain things so I'll try get out of that :+1:

**Pull request merged**
